#!/usr/bin/env bash
# --draft
port=4000

while (($#)); do
  case "$1" in
  -p | --port)
    port="$2"
    shift 2
    ;;
  *)
    echo "Unknown option: '$1'" >&2
    exit 1
    ;;
  esac
done

exec bundle exec jekyll serve --livereload --draft --host 0.0.0.0 --port "$port"